# Site settings
title: Johnattan Garcia Ruiz
description: >-
  Global Health Researcher, Health Policy Expert, affiliated with Harvard T.H. Chan
  School of Public Health. Specializing in pharmaceutical policy, health systems,
  and access to medicines in Latin America.

author:
  name: Johnattan Garcia Ruiz
  credentials: MPH, MBA, LL.B.
  email: # Add email if you want to display it
  twitter: GarciaRuizJo
  linkedin: johnattangarcia
  google_scholar: 7JZVw_YAAAAJ

# Build settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://j-garciaruiz.github.io" # the base hostname & protocol for your site

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Johnattan Garcia Ruiz"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Include
include:
  - _pages

# Site navigation
navigation:
  - title: About
    url: /#about
  - title: Education
    url: /#education
  - title: Publications
    url: /publications.html
  - title: Visualizations
    url: /visualizations.html
  - title: Insights
    url: /blog.html
  - title: Experience
    url: /#experience
  - title: Contact
    url: /#contact
